TRASH(1)

# NAME

trash - very secure restricted shell /s 

# SYNOPSIS

*trash*

# DESCRIPTION

The trash utility is a "secure shell" implementation that provides a secure
way to interact with some critical and dumb system. It requires some utilities
such as _man_(7) and _ping_(8).

# ENVIRONMENT

The trash utility supports _TRASHDIR_ directory for filesystem actions.

# SEE ALSO

_bash_(1)

# AUTHORS

Written by Cale Black <poptart@hosakacorp.net>.
